name: Build

on:
  push:
    branches: [ develop ]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build with dotnet
      working-directory: .\BardMusicPlayer
      run: dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained false -c Release

    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: BardMusicPlayer
        path: BardMusicPlayer\bin\Release\net7.0-windows\win-x64\publish\BardMusicPlayer.exe
        if-no-files-found: error
        retention-days: 1
