name: Build

on:
  push:
    branches: [ develop ]

jobs:

  build:
    runs-on: windows-latest

    env:
      Solution_Name: BardMusicPlayer

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build with dotnet
      run: dotnet publish --configuration Release

    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: BardMusicPlayer
        path: BardMusicPlayer\bin\Release\net7.0-windows\win-x64\*.exe
        if-no-files-found: error
        retention-days: 1
